// List of adjectives for the DAO name
export const adjectives = ["Snapping", "Mystic", "Roaring", "Ethereal", "Radiant", "Whispering", "Dancing", "Hidden", "Wandering", "Ancient",
              "Shining", "Crimson", "Silent", "Golden", "Dreaming", "Daring", "Thundering", "Celestial", "Swift", "Blazing",
              "Frozen", "Serene", "Vibrant", "Glowing", "Harmonic", "Twilight", "Forgotten", "Spirited", "Emerald", "Fiery",
              "Majestic", "Azure", "Stellar", "Infinite", "Mysterious", "Arcane", "Dynamic", "Stormy", "Eternal", "Solar",
              "Cosmic", "Enchanted", "Phantom", "Divine", "Rustic", "Sapphire", "Fabled", "Galactic", "Harmonious", "Luminous",
              "Nebulous", "Opulent", "Prismatic", "Quirky", "Revered", "Stoic", "Tranquil", "Umbral", "Vivid", "Whimsical",
              "Exotic", "Yielding", "Zenith", "Ambitious", "Boundless", "Curious", "Diligent", "Empowered", "Flourishing",
              "Gracious", "Hopeful", "Inquisitive", "Joyful", "Kindred", "Limitless", "Mindful", "Nurturing", "Optimistic",
              "Prosperous", "Questful", "Resilient", "Soulful", "Thriving", "Unified", "Virtuous", "Wise", "Xenial", "Youthful",
              "Zealous", "Abundant", "Bountiful", "Creative", "Dynamic", "Evolving", "Fruitful", "Generous", "Hearty", "Intrepid",
              "Jubilant", "Keen", "Lively", "Miraculous", "Noble", "Organic", "Plentiful", "Quintessential", "Robust", "Sustainable",
              "Thorough", "Upbeat", "Valiant", "Warmhearted", "Xtraordinary", "Yielding", "Zestful"]

// List of nouns for the DAO name
export const nouns = ["Goldfish", "Dragons", "Phoenix", "Unicorns", "Wolves", "Griffins", "Sphinxes", "Titans", "Voyagers", "Pioneers",
         "Warriors", "Guardians", "Seekers", "Mages", "Knights", "Sages", "Explorers", "Wanderers", "Champions", "Artisans",
         "Creators", "Dreamers", "Visionaries", "Innovators", "Builders", "Thinkers", "Scholars", "Mystics", "Navigators",
         "Artists", "Crafters", "Seers", "Oracles", "Sorcerers", "Shamans", "Wizards", "Enchanters", "Catalysts", "Trailblazers",
         "Adventurers", "Curators", "Healers", "Alchemists", "Architects", "Pilots", "Commanders", "Chiefs", "Barons", "Emperors",
         "Kings", "Queens", "Princes", "Princesses", "Dukes", "Duchesses", "Lords", "Ladies", "Sultans", "Shahs", "Caliphs",
         "Rajas", "Maharajas", "Samurais", "Ninjas", "Pirates", "Vikings", "Cavaliers", "Paladins", "Rangers", "Druids", "Bards",
         "Minstrels", "Troubadours", "Poets", "Writers", "Sculptors", "Painters", "Actors", "Dancers", "Musicians", "Composers",
         "Singers", "Conductors", "Magicians", "Illusionists", "Clowns", "Jesters", "Acrobats", "Athletes", "Gymnasts", "Skaters",
         "Surfers", "Divers", "Swimmers", "Runners", "Racers", "Climbers", "Hikers", "Trekkers", "Backpackers", "Travelers",
         "Tourists", "Globetrotters", "Vagabonds", "Nomads", "Wanderlusts", "Jetsetters", "Explorers", "Discoverers", "Inventors",
         "Pioneers", "Trailblazers", "Pathfinders", "Guides", "Scouts", "Navigators", "Pilots", "Astronauts", "Cosmonauts"]

export const communityTypes = [
"Art",
"Science",
"Book",
"Gardening",
"Chess",
"Coding",
"Cooking",
"Dance",
"Debate",
"Drama",
"Entrepreneurship",
"Environmental",
"Film",
"Fitness",
"Gaming",
"History",
"Investment",
"Jazz",
"Knitting",
"Language",
"Magic",
"Math",
"Meditation",
"Music",
"Nature",
"Origami",
"Photography",
"Poetry",
"Robotics",
"Running",
"Sailing",
"Skiing",
"Soccer",
"Space",
"Surfing",
"Technology",
"Travel",
"Trivia",
"Vegan",
"Wine",
"Writing",
"Yoga",
"Zoology",
"Archery",
"Astronomy",
"Baking",
"Ballet",
"Birdwatching",
"Calligraphy",
"Camping",
"Ceramics",
"Cycling",
"Digital Art",
"Diving",
"Drawing",
"Equestrian",
"Fashion",
"Fencing",
"Fishing",
"Folk Music",
"Genealogy",
"Geocaching",
"Golf",
"Hiking",
"Improv",
"Journalism",
"Kayaking",
"Kite Surfing",
"Martial Arts",
"Metalworking",
"Model Building",
"Mountaineering",
"Needlework",
"Orienteering",
"Painting",
"Parkour",
"Philately",
"Philosophy",
"Photography",
"Pilates",
"Pottery",
"Quilting",
"Radio Control",
"Rafting",
"Rock Climbing",
"Role Playing Games",
"Rowing",
"Scuba Diving",
"Sculpture",
"Skateboarding",
"Snorkeling",
"Snowboarding",
"Social Media",
"Stand-Up Comedy",
"Tai Chi",
"Tea",
"Ultimate Frisbee",
"Video Production",
"Virtual Reality",
"Volunteering"]
// "List 2: Target Audiences or Themes",
export const targetAudiences = [
"Beginners",
"Professionals",
"Children",
"Teenagers",
"Adults",
"Seniors",
"Families",
"Women",
"Men",
"Couples",
"Students",
"Entrepreneurs",
"Artists",
"Writers",
"Musicians",
"Travelers",
"Environmentalists",
"Foodies",
"History Buffs",
"Tech Enthusiasts",
"Fitness Fans",
"Animal Lovers",
"Nature Enthusiasts",
"Film Buffs",
"Adventure Seekers",
"Science Geeks",
"Language Learners",
"DIY Enthusiasts",
"Crafters",
"Photographers",
"Yoga Practitioners",
"Meditation Enthusiasts",
"Comedy Lovers",
"Fantasy Fans",
"Mystery Lovers",
"Thriller Enthusiasts",
"Horror Fans",
"Romance Readers",
"Sci-Fi Aficionados",
"Non-fiction Admirers",
"Poetry Devotees",
"Classic Literature Fans",
"Modern Literature Followers",
"Comic Book Enthusiasts",
"Manga Readers",
"Anime Fans",
"Video Gamers",
"Board Gamers",
"Strategy Game Lovers",
"Puzzle Solvers",
"Chess Players",
"Card Game Aficionados",
"Sports Fans",
"Golfers",
"Runners",
"Cyclists",
"Swimmers",
"Skiers",
"Snowboarders",
"Surfers",
"Divers",
"Hikers",
"Campers",
"Rock Climbers",
"Kayakers",
"Sailing Enthusiasts",
"Fishermen",
"Hunters",
"Archers",
"Martial Artists",
"Dancers",
"Gymnasts",
"Fitness Trainers",
"Health Conscious Individuals",
"Vegans",
"Vegetarians",
"Gluten-Free Dieters",
"Organic Food Advocates",
"Wine Connoisseurs",
"Beer Aficionados",
"Coffee Enthusiasts",
"Tea Lovers",
"Chocolate Admirers",
"Bakers",
"Chefs",
"Home Cooks",
"Culinary Experts",
"Gourmet Foodies",
"Travel Photographers",
"Urban Explorers",
"Rural Adventure Seekers",
"Beach Lovers",
"Mountain Enthusiasts",
"City Dwellers",
"Country Folks",
"Digital Nomads",
"Remote Workers",
"Freelancers",
"Entrepreneurs",
"Innovators"]

const getRandomElement = (array: string[]): string => {
    return array[Math.floor(Math.random() * array.length)];
};

export const getRandomName = () => {
    return `${getRandomElement(adjectives)} ${getRandomElement(nouns)}`
}

export const getRandomDescription = () => {
    return `Welcome to our ${getRandomElement(communityTypes)} club for ${getRandomElement(targetAudiences)}.`
}